### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Zed-bf** [WW-Tong/ssagcn_for_path_prediction#2]
在测试文件中，为什么在print ADE和FDE时除以scale.已经在之前除过了

**Comment by Chenzhou727** [comment]
你知道原因了吗，我也有相同的疑惑

**Comment by Zed-bf** [comment]
> 你知道原因了吗，我也有相同的疑惑

想一想这么简单的模型凭什么性能这么好，可能就知道是什么情况了

**Comment by Chenzhou727** [comment]
你在啊，他们还有一篇BIP-Tree,我以前看的，也是今年的，你看过没有，

**Comment by Zed-bf** [comment]
> e,我以前看的，也是今年的，你看过没有

没看过

**Comment by Chenzhou727** [comment]
BIP-Tree: Tree Variant With Behavioral Intention Perception for Heterogeneous Trajectory Prediction

**Comment by zyz111** [comment]
感谢您对我们工作的关注，非常抱歉之前代码上传版本有误，正确的代码近两天上传，请及时查阅。

**Comment by Jasmine302** [comment]
在训练的时候，加载数据集阶段报这个错误，怎么解决呢？
Traceback (most recent call last):
  File "F:/paper_code/ssagcn_for_path_prediction-main/SSAGCN/1.py", line 2, in <module>
    model = torch.load('./data/eth_test.pt')
  File "D:\anaconda\envs\pytorch_11.3\lib\site-packages\torch\serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\anaconda\envs\pytorch_11.3\lib\site-packages\torch\serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by WW-Tong** [comment]
> 在训练的时候，加载数据集阶段报这个错误，怎么解决呢？ Traceback (most recent call last): File "F:/paper_code/ssagcn_for_path_prediction-main/SSAGCN/1.py", line 2, in model = torch.load('./data/eth_test.pt') File "D:\anaconda\envs\pytorch_11.3\lib\site-packages\torch\serialization.py", line 713, in load return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args) File "D:\anaconda\envs\pytorch_11.3\lib\site-packages\torch\serialization.py", line 920, in _legacy_load magic_number = pickle_module.load(f, **pickle_load_args) _pickle.UnpicklingError: invalid load key, 'v'.

不太清楚你的1.py 的内容，根据提示 line 2, in model = torch.load('./data/eth_test.pt') 你似乎在尝试把数据加载到模型中，这显然会报错

**Comment by Jasmine302** [comment]
> > 在训练的时候，加载数据集阶段报这个错误，怎么解决呢？ Traceback (most recent call last): File "F:/paper_code/ssagcn_for_path_prediction-main/SSAGCN/1.py", line 2, in model = torch.load('./data/eth_test.pt') File "D:\anaconda\envs\pytorch_11.3\lib\site-packages\torch\serialization.py", line 713, in load return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args) File "D:\anaconda\envs\pytorch_11.3\lib\site-packages\torch\serialization.py", line 920, in _legacy_load magic_number = pickle_module.load(f, **pickle_load_args) _pickle.UnpicklingError: invalid load key, 'v'.
> 
> 不太清楚你的1.py 的内容，根据提示 line 2, in model = torch.load('./data/eth_test.pt') 你似乎在尝试把数据加载到模型中，这显然会报错

不好意思。1.py是我在测试的时候使用的，直接clone下来这个代码后运行train.py也会报如下错误
Traceback (most recent call last):
  File "F:/paper_code/ssagcn_for_path_prediction-main/SSAGCN/train.py", line 56, in <module>
    loader_train = torch.load("./data/" + args.dataset + "_train.pt")
  File "D:\anaconda\envs\pytorch_11.3\lib\site-packages\torch\serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\anaconda\envs\pytorch_11.3\lib\site-packages\torch\serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by WW-Tong** [comment]
抱歉，刚注意到上传的数据由于lfs 服务到期失效了，我会尽快续费或者是转储到其他网盘中














在 2023-11-28 20:36:45，"Jasmine" ***@***.***> 写道：

在训练的时候，加载数据集阶段报这个错误，怎么解决呢？ Traceback (most recent call last): File "F:/paper_code/ssagcn_for_path_prediction-main/SSAGCN/1.py", line 2, in model = torch.load('./data/eth_test.pt') File "D:\anaconda\envs\pytorch_11.3\lib\site-packages\torch\serialization.py", line 713, in load return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args) File "D:\anaconda\envs\pytorch_11.3\lib\site-packages\torch\serialization.py", line 920, in _legacy_load magic_number = pickle_module.load(f, **pickle_load_args) _pickle.UnpicklingError: invalid load key, 'v'.

不太清楚你的1.py 的内容，根据提示 line 2, in model = torch.load('./data/eth_test.pt') 你似乎在尝试把数据加载到模型中，这显然会报错

不好意思。1.py是我在测试的时候使用的，直接clone下来这个代码后运行train.py也会报如下错误
Traceback (most recent call last):
File "F:/paper_code/ssagcn_for_path_prediction-main/SSAGCN/train.py", line 56, in
loader_train = torch.load("./data/" + args.dataset + "_train.pt")
File "D:\anaconda\envs\pytorch_11.3\lib\site-packages\torch\serialization.py", line 713, in load
return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
File "D:\anaconda\envs\pytorch_11.3\lib\site-packages\torch\serialization.py", line 920, in _legacy_load
magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by Jasmine302** [comment]
> 注意到上传的数据由于lfs 服务到期失效了，我会尽快续费或者是转储到其他网盘中

好的，非常感谢！

**Comment by WW-Tong** [comment]
> > 注意到上传的数据由于lfs 服务到期失效了，我会尽快续费或者是转储到其他网盘中
> 
> 好的，非常感谢！
数据在这里
链接：https://pan.baidu.com/s/1oSHxefebEtslHEfrOwlPRQ?pwd=aq7u 
提取码：aq7u

**Comment by Jasmine302** [comment]
> > > 注意到上传的数据由于lfs 服务到期失效了，我会尽快续费或者是转储到其他网盘中
> > 
> > 
> > 好的，非常感谢！
> > 数据在这里
> > 链接：https://pan.baidu.com/s/1oSHxefebEtslHEfrOwlPRQ?pwd=aq7u
> > 提取码：aq7u

非常感谢！还有注意到在计算加权邻接矩阵关系的时候，社会软注意函数Fssa是在预处理部分实现的，可否提供一下数据处理部分的代码呢？

**Comment by Pranav-chib** [comment]
Please can you share the other link, the link provided does not work outside china. Baidu does not works. 
thankyou for the repo.
